UKRTB_journal/Controllers/FilesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using UKRTB_journal.Models;
using UKRTB_journal.ViewModels;
using MimeKit;
using MailKit.Net.Smtp;
using MailKit.Security;
using System.Net;
using Distinct.Telemedicine.Contracts.Models;
using Microsoft.AspNetCore.Authorization;
using UKRTB_journal.Services;

namespace UKRTB_journal.Controllers
{
    public class FilesController : Controller
    {
        private readonly ILogger<FilesController> _logger;
        ApplicationContext _context;
        IWebHostEnvironment _appEnvironment;
        IConfiguration Configuration { get; }
        private EmailSettings _emailSettings;
        IInfoService infoService;
        bool isSaveFiles;
        public FilesController(ApplicationContext context, ILogger<FilesController> logger, IWebHostEnvironment appEnvironment, IConfiguration configuration, IInfoService infoService)
        {
            _context = context;
            _logger = logger;
            _appEnvironment = appEnvironment;
            Configuration = configuration;
            this.infoService = infoService;
            Configuration.GetValue<string>("isSaveFiles");
        }

        public IActionResult Privacy()
        {
            return View();
        }


        [HttpGet("files/upload")]
        [Authorize(Roles = "admin, student")]
        public IActionResult UploadFileView(int? groupId)
        {
            var students = _context.Students.Where(x => groupId == null || x.GroupId == groupId).ToList();
            ViewBag.Groups = _context.Groups.Select(x => new GroupModel { Id = x.Id, Name = x.Name }).ToList();

            ViewBag.Students = new SelectList(students, "Id", "Surname");

            return View("/Views/Files/Create.cshtml");
        }

        [HttpGet]
        public IActionResult FilesView(int? groupId, int? studentId)
        {
            var files = _context.Files
                .Where(x => studentId == null || x.StudentId == studentId)
                .Where(x => groupId == null || x.GroupId == groupId).ToList();
            var student = _context.Students.FirstOrDefault(x => x.Id == studentId);
            var students = new List<StudentModel>();
            if (student is null)
            {
                students = _context.Students
                    .Where(x => groupId == null || x.GroupId == groupId)
                 .Select(x => new StudentModel { Id = x.Id, Surname = x.Surname, Name = x.Name, GroupId = x.GroupId }).ToList();
            }
            else
            {
                students = _context.Students
                    .Where(x => x.GroupId == groupId || (student != null & x.GroupId == student.GroupId))
                    .Select(x => new StudentModel { Id = x.Id, Surname = x.Surname, Name = x.Name, GroupId = x.GroupId }).ToList();
            }
            
            var groups = _context.Groups.Select(x => new GroupModel { Id = x.Id, Name = x.Name }).ToList();

            return View("/Views/Files/Files.cshtml", new FilesViewModel { GroupId = groupId, StudentId = studentId, Files = files, Students = students, Groups = groups });
        }

        [HttpGet("files/edit")]
        [Authorize(Roles = "admin, student")]
        public async Task<IActionResult> EditFilesView(int fileId)
        {
            var file = await _context.Files.FirstOrDefaultAsync(x => x.Id == fileId);
            ViewBag.Students = _context.Students.Select(x => new StudentModel { Id = x.Id, Surname = x.Surname, Name = x.Name, GroupId = x.GroupId }).ToList();
            ViewBag.Groups = _context.Groups.Select(x => new GroupModel { Id = x.Id, Name = x.Name }).ToList();
            return View("/Views/Files/Edit.cshtml", new FileWithInfo { FileDescription = file });
        }

        [HttpGet("files/mark")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> MarkFilesView(int fileId)
        {
            var file = await _context.Files.FirstOrDefaultAsync(x => x.Id == fileId);

            return View("/Views/Files/Mark.cshtml", new FileWithInfo { FileDescription = file });
        }

        [HttpGet("files/delete")]
        [Authorize(Roles = "admin, student")]
        public async Task<IActionResult> DeleteFileView(int? fileId)
        {
            var file = await _context.Files.FirstOrDefaultAsync(x => x.Id == fileId);

            return View("/Views/Files/Delete.cshtml", file);
        }

        [HttpPost("files/upload")]
        [Authorize(Roles = "admin, student")]
        public async Task<IActionResult> UploadFile(FileWithInfo fileDto)
        {
            if (fileDto != null)
            {
                var sameFile = await _context.Files.FirstOrDefaultAsync(x =>
                        x.FileNumberForType == fileDto.FileDescription.FileNumberForType &&
                        x.Type == fileDto.FileDescription.Type &&
                        x.StudentId == fileDto.FileDescription.StudentId
                    );
                if (sameFile != null)
                {
                    fileDto.FileDescription.Version = sameFile.Version + 1;
                }
                else
                {
                    fileDto.FileDescription.Version = 1;
                }
                
                fileDto.FileDescription.GroupId = _context.Students.FirstOrDefault(x => x.Id == fileDto.FileDescription.StudentId)?.GroupId ?? 1;

                var path = GetPath(fileDto);
                fileDto.FileDescription.Path = path;
                fileDto.FileDescription.UploadDate = DateTime.Now;

                _context.Files.Add(fileDto.FileDescription);
                
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await fileDto.File.CopyToAsync(fileStream);
                }

                await _context.SaveChangesAsync();
                
                Send(fileDto);
                if (!isSaveFiles)
                {
                    var fileInfo = new FileInfo(_appEnvironment.WebRootPath + fileDto.FileDescription.Path);
                    if (fileInfo != null)
                    {
                        fileInfo.Delete();
                    }
                }
            }

            return RedirectToAction("FilesView");
        }

        [HttpPost("files/edit/{filedescription.id}")]
        [Authorize(Roles = "admin, student")]
        public async Task<IActionResult> EditFile(FileWithInfo fileDto)
        {
            if (fileDto != null)
            {
                FileDescription file = await _context.Files.FirstOrDefaultAsync(p => p.Id == fileDto.FileDescription.Id);
                file.Version++;

                file.StudentId = fileDto.FileDescription.StudentId;
                file.GroupId = fileDto.FileDescription.GroupId;
                file.FileNumberForType = fileDto.FileDescription.FileNumberForType;
                file.Type = fileDto.FileDescription.Type;
                file.EditDate = DateTime.Now;

                _context.Files.Update(file);
                _context.SaveChanges();
            }

            return RedirectToAction("FilesView");
        }

        [HttpPost("files/mark/{filedescription.id}")]
        [Authorize(Roles = "admin, student")]
        public async Task<IActionResult> MarkFile(FileWithInfo fileDto)
        {
            if (fileDto != null)
            {
                FileDescription file = await _context.Files.FirstOrDefaultAsync(p => p.Id == fileDto.FileDescription.Id);
                file.Mark = fileDto.FileDescription.Mark;

                _context.Files.Update(file);
                _context.SaveChanges();
            }

            return RedirectToAction("FilesView");
        }

        [HttpPost("files/delete")]
        [Authorize(Roles = "admin, student")]
        public async Task<IActionResult> DeleteFile(int? fileId)
        {
            if (fileId != null)
            {
                FileDescription file = await _context.Files.FirstOrDefaultAsync(p => p.Id == fileId);
                if (file != null)
                {
                    _context.Files.Remove(file);
                    await _context.SaveChangesAsync();

                    var fileInfo = new FileInfo(_appEnvironment.WebRootPath + file.Path);
                    if (fileInfo != null)
                    {
                        fileInfo.Delete();
                    }

                    return RedirectToAction("FilesView");
                }
            }

            return NotFound();
        }

        private async void Send(FileWithInfo file)
        {
            _emailSettings = new EmailSettings()
            {
                Host = Configuration.GetValue<string>("smtpHost"),
                Port = Configuration.GetValue<int>("smtpPort"),
                Username = Configuration.GetValue<string>("smtpUsername"),
                Password = Configuration.GetValue<string>("smtpPassword"),
                From = Configuration.GetValue<string>("smtpFrom"),
                Sender = Configuration.GetValue<string>("SystemMainName"),
                Email = Configuration.GetValue<string>("smtpEmail")
            };
            var emailMessage = new MimeMessage();
            emailMessage.From.Add(new MailboxAddress(_emailSettings.Sender, _emailSettings.From));
            emailMessage.To.Add(new MailboxAddress("", _emailSettings.Email));
            emailMessage.Subject = $"{infoService.GetStudentSurName(file.FileDescription.StudentId)} {infoService.GetGroupName(file.FileDescription.GroupId)} {file.FileDescription.Type} {file.FileDescription.FileNumberForType}";
            var builder = new BodyBuilder();


            builder.TextBody = $"{file.FileDescription.Description}";

            // We may also want to attach a calendar event for Monica party...

UKRTB_journal/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UKRTB_journal.Models;
using UKRTB_journal.ViewModels;

namespace UKRTB_journal.Controllers
{
    [Route("students")]
    public class StudentsController : Controller
    {
        private readonly ILogger<StudentsController> _logger;
        ApplicationContext _context;
        IWebHostEnvironment _appEnvironment;

        public StudentsController(ApplicationContext context, ILogger<StudentsController> logger, IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _logger = logger;
            _appEnvironment = appEnvironment;
        }

        [HttpGet]
        public async Task<IActionResult> StudentsView(int? groupId)
        {
            List<Student> students;
            if(groupId != null)
            {
                students = _context.Students.Where(x => x.GroupId == groupId).ToList();
            }
            else
            {
                students = _context.Students.ToList();
            }
            ViewBag.Groups = _context.Groups.Select(x => new GroupModel { Id = x.Id, Name = x.Name}).ToList();


            return View("/Views/Students/Students.cshtml", students);
        }

        [HttpGet("create")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddStudentView()
        {
            var groups = await _context.Groups.ToListAsync();
            ViewBag.Groups = new SelectList(groups, "Id", "Name");

            return View("/Views/Students/Create.cshtml");
        }

        [HttpGet("edit")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> EditStudentView(int studentId)
        {
            var student = await _context.Students.FirstOrDefaultAsync(x => x.Id == studentId);

            ViewBag.Groups = _context.Groups.Select(x => new GroupModel { Id = x.Id, Name = x.Name }).ToList();

            return View("/Views/Students/Edit.cshtml", student);
        }

        [HttpGet("delete")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteStudentView(int? studentId)
        {
            var student = await _context.Students.FirstOrDefaultAsync(x => x.Id == studentId);

            return View("/Views/Students/Delete.cshtml", student);
        }

        [HttpPost("create")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddStudent(Student studentDto)
        {
            if(studentDto != null)
            {
                _context.Students.Add(studentDto);
                _context.SaveChanges();
            }
            
            return RedirectToAction("StudentsView");
        }

        [HttpPost("edit/{id}")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> EditStudent(Student studentDto)
        {
            _context.Students.Update(studentDto);
            await _context.SaveChangesAsync();

            return RedirectToAction("StudentsView");
        }

        [HttpPost("delete")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteStudent(int? studentId)
        {
            if (studentId != null)
            {
                Student student = await _context.Students.FirstOrDefaultAsync(p => p.Id == studentId);
                if (student != null)
                {
                    _context.Students.Remove(student);
                    await _context.SaveChangesAsync();

                    return RedirectToAction("StudentsView");
                }
            }

            return NotFound();
        }
    }
}

UKRTB_journal/Views/Students/Create.cshtml
@model UKRTB_journal.Models.Student
@{
    ViewBag.Title = "Добавление студента";
}
<form asp-action="Create" asp-controller="Students">
    <div class="validation" asp-validation-summary="ModelOnly"></div>
    <div class="form-group">
        <label asp-for="Surname" class="control-label">Фамилия</label>
        <input type="text" asp-for="Surname" class="form-control" /><br />
        <span asp-validation-for="Surname"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name" class="control-label">Имя</label>
        <input type="text" asp-for="Name" class="form-control" /><br />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="GroupId" class="control-label">Группа</label><br />
        <select asp-for="GroupId" asp-items="@ViewBag.Groups">
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" /><br />
        <span asp-validation-for="Email"></span>
    </div>
    <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Добавить" />
    </div>
</form>

@section scripts
{
    <script src="~/lib/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

UKRTB_journal/Views/Students/Delete.cshtml
@model UKRTB_journal.Models.Student

@inject UKRTB_journal.Services.IInfoService InfoService
@{
    ViewBag.Title = "Удаление студента";
}

<div>
    <dl class="dl-horizontal">
        <dt>Имя</dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>Фамилия</dt>
        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt>Группа</dt>
        <dd>
            @InfoService.GetGroupName(@Model.GroupId)
        </dd>
        <dt>Email</dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>

    <div>
        <form asp-controller="Students" asp-action="Delete" asp-route-studentId="@Model.Id" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Удалить" />
            </div>
        </form>
    </div>
</div>

UKRTB_journal/Views/Students/Edit.cshtml
@model UKRTB_journal.Models.Student
@inject UKRTB_journal.Services.IInfoService InfoService
@{
    ViewBag.Title = "Редактирование студента";
}
<form asp-action="Edit" asp-controller="Students" asp-route-id="@Model.Id" method="post">
    <div class="form-group">
        <label asp-for="Surname" class="control-label">Фамилия</label>
        <input type="text" value="@Model.Surname" asp-for="Surname" class="form-control" /><br />
        <span asp-validation-for="Surname"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name" class="control-label">Имя</label>
        <input type="text" value="@Model.Name" asp-for="Name" class="form-control" /><br />
        <span asp-validation-for="Name"></span>
    </div>
    <label>Выберите группу</label>
    <select name="groupId" class="form-select">
        @foreach (UKRTB_journal.ViewModels.GroupModel group in @ViewBag.Groups)
        {
            if (Model.GroupId != null && Model.GroupId == group.Id)
            {
                <option selected="selected" value="@group.Id">@group.Name</option>
            }
            else
            {
                <option value="@group.Id">@group.Name</option>
            }
        }
    </select>
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="text" value="@Model.Email" asp-for="Email" class="form-control" /><br />
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-primary" />
    </div>
</form>
@section scripts
{
    <script src="~/lib/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

UKRTB_journal/Views/Students/Students.cshtml
@model IEnumerable<UKRTB_journal.Models.Student>
@inject UKRTB_journal.Services.IInfoService InfoService
@{
    ViewBag.Title = "Все студенты";
}
<form class="form-inline">
    <label>Выберите группу&nbsp;</label>
    <select name="groupId" class="form-select">
        @foreach (UKRTB_journal.ViewModels.GroupModel group in ViewBag.Groups)
        {
            if (ViewBag.GroupId != null && ViewBag.GroupId == group.Id)
            {
                <option selected="selected" value="@group.Id">@group.Name</option>
            }
            else
            {
                <option value="@group.Id">@group.Name</option>
            }
        }
    </select>
    &nbsp;<input type="submit" class="btn btn-primary" value="Выбрать" /> 
</form>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <td scope="col" align="center">Имя:</td>
            <td scope="col" align="center">Фамилия:</td>
            <td scope="col" align="center">Email:</td>
            <td scope="col" align="center">Действия:</td>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td align="center">@item.Surname</td>
            <td align="center">@item.Name</td>
            <td align="center">@item.Email</td>
            <td align="center">
                <a asp-action="FilesView" asp-controller="Files" asp-route-studentId="@item.Id">Все работы</a> |
                <a asp-action="Edit" asp-controller="Students" asp-route-studentId="@item.Id">Изменить</a> |
                <a asp-action="Delete" asp-controller="Students" asp-route-studentId="@item.Id">Удалить</a>
            </td>
        </tr>
    }
</table>
<a asp-action="Create">Добавить пользователя</a>