UKRTB_journal/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UKRTB_journal.Models;
using UKRTB_journal.ViewModels;

namespace UKRTB_journal.Controllers
{
    [Route("users")]
    public class UsersController : Controller
    {
        private readonly ILogger<FilesController> _logger;
        ApplicationContext _context;
        IWebHostEnvironment _appEnvironment;

        public UsersController(ApplicationContext context, ILogger<FilesController> logger, IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _logger = logger;
            _appEnvironment = appEnvironment;
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UsersView()
        {
            var users = await _context.Users.ToListAsync();

            return View("/Views/Users/Users.cshtml", users);
        }

        [HttpGet("create")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddUserView(int? groupId)
        {
            var students = _context.Students.Where(x => groupId == null || x.GroupId == groupId).ToList();
            ViewBag.Groups = _context.Groups.Select(x => new GroupModel { Id = x.Id, Name = x.Name }).ToList();

            ViewBag.Students = new SelectList(students, "Id", "Surname");
            return View("/Views/Users/Create.cshtml");
        }

        [HttpGet("edit")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> EditUserView(int userId)
        {
            var users = await _context.Users.FirstOrDefaultAsync(x => x.Id == userId);

            return View("/Views/Users/Edit.cshtml", users);
        }

        [HttpGet("delete")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteUserView(int? userId)
        {
            var user = await _context.Users.FirstOrDefaultAsync(x => x.Id == userId);

            return View("/Views/Users/Delete.cshtml", user);
        }

        [HttpPost("create")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddUser(User userDto)
        {
            _context.Users.Add(userDto);
            _context.SaveChanges();

            return RedirectToAction("UsersView");
        }

        [HttpPost("edit/{id}")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> EditUser(User userDto)
        {
            _context.Users.Update(userDto);
            await _context.SaveChangesAsync();

            return RedirectToAction("UsersView");
        }

        [HttpPost("delete")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? userId)
        {
            if (userId != null)
            {
                User user = await _context.Users.FirstOrDefaultAsync(p => p.Id == userId);
                if (user != null)
                {
                    _context.Users.Remove(user);
                    await _context.SaveChangesAsync();

                    return RedirectToAction("UsersView");
                }
            }

            return NotFound();
        }
    }
}

UKRTB_journal/Views/Users/Create.cshtml
@model UKRTB_journal.Models.User
@{
    ViewBag.Title = "Регистрация";
}
<form class="form-inline">
    <label>Выберите группу&nbsp;</label>
    <select name="groupId" class="form-select">
        @foreach (UKRTB_journal.ViewModels.GroupModel group in @ViewBag.Groups)
        {
            <option value="@group.Id">@group.Name</option>
        }
    </select>
    &nbsp;<input type="submit" class="btn btn-primary" value="Выбрать" /> <br />
</form>
<form asp-action="Create" asp-controller="Users">
    <div class="validation" asp-validation-summary="ModelOnly"></div>
    <div class="form-group">
        <label asp-for="StudentId" class="control-label">Студент</label><br />
        <select asp-for="StudentId" asp-items="@ViewBag.Students" class="form-control">
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" name="email" /><br />
        <span asp-validation-for="Email"></span>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="control-label">Пароль</label>
        <input type="text" asp-for="Password" class="form-control" type="password" name="password" /><br />
        <span asp-validation-for="Password"></span>
    </div>
    <div class="form-group">
        <label asp-for="IsAdmin" class="control-label">Админ</label>
        &nbsp;<input type="checkbox" asp-for="IsAdmin" value="false" /><br />
        <span asp-validation-for="IsAdmin"></span>
    </div>
    <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Добавить" />
    </div>
</form>

@section scripts
{
    <script src="~/lib/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}